# Pandas的数据结构介绍

In [1]:
import pandas as pd
import numpy as np

In [2]:
from pandas import Series, DataFrame

## Series

Series是一种类似于一堆数组的对象，它由一组数据（各种Numpy数据类型）以及一组与之相关的数据标签（即索引\index）组成。仅由一组数据即可产生最简单的Series：

In [3]:
obj = pd.Series([4,7,-5,3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

Series的字符串表示为：index在左边，values在右边。  
没有创建指定索引，系统会写一个0到N-1的整数型索引。

In [5]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj.index # like range(4)

RangeIndex(start=0, stop=4, step=1)

自己创建Series的索引：

In [7]:
obj2 = pd.Series([4,7,-5,3], index=['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [8]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [9]:
obj2['a']

-5

In [10]:
obj2['b']=6
obj2

d    4
b    6
a   -5
c    3
dtype: int64

In [11]:
obj2[['c','a','d']]

c    3
a   -5
d    4
dtype: int64

使用Numpy函数或类似Numpy的运算都会保留索引值的链接：

In [12]:
obj2[obj2>0]

d    4
b    6
c    3
dtype: int64

In [13]:
obj*2

0     8
1    14
2   -10
3     6
dtype: int64

In [14]:
np.exp(obj2)

d     54.598150
b    403.428793
a      0.006738
c     20.085537
dtype: float64

也可以把Series看成一个定长的有序字典，因为它是索引值到数据值的一个映射。  
它可以用在许多原本需要字典参数的函数中：

In [15]:
'b' in obj2

True

In [16]:
'e' in obj2

False

也可以直接通过一个Python字典来创建Series：

In [17]:
sdata = {'Ohio':35000, 'Texas':71000, 'Oregon':16000, 'Utah':5000}

In [18]:
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

也可以手动改变字典的顺序：

In [19]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [20]:
obj4 = pd.Series(sdata, index=states)

In [21]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

使用pd.innull 或pd.notnull来检测缺失数据：

In [22]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [23]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

Series也有类似的实例方法：

In [24]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

Series最重要的一个功能是，会根据运算的索引标签自动对齐数据：

In [25]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [26]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [27]:
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

Series对象本身及其索引都有一个name属性，根pandas其他的关键功能关系非常密切：

In [28]:
obj4.name = 'population'

In [29]:
obj4.index.name = 'state'

In [30]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

index可以通过赋值的方式直接修改：

In [31]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [32]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

## DataFrme

最常用的创建方式是直接传入一个由等长列表或Numpy数组组成的字典：

In [33]:
data = {'state':['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year':[2000, 2001, 2002, 2001, 2002, 2003],
        'pop':[1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [34]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [35]:
frame.head() # 取前五项

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [36]:
pd.DataFrame(data, columns=['year', 'state', 'pop']) # 按照指定顺序排列

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [37]:
frame2 = pd.DataFrame(data,columns=['year', 'state', 'pop', 'debt',],      # 找不到就会产生缺失值
                      index=['one', 'two', 'three', 'four', 'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [38]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [39]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [40]:
frame2['year']

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

Note: IPython提供了类似属性的访问（即frame2.year）和tab补全。  
frame2[column]适用于任何列的名，但是frame2.column只有在列名是一个合理的Python变量名时才适用。

行也可以通过位置或名称的方式进行获取，比如用loc属性：

In [41]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

列也可以通过赋值的方式进行修改：

In [42]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [43]:
frame2['debt']=np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

将列表或数组赋值给某个列时，其长度必须跟DataFrame的长度相匹配。  
如果赋值的是一个series，就会精确匹配DataFrame的索引，所有的空位都将被填上缺失值：

In [44]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [45]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [46]:
del frame2['eastern']  # 删除列
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

另一种常见的数据形式是嵌套字典：

In [47]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
    'Ohio': {2000:1.5, 2001:1.7, 2002:3.6}}

如果嵌套字典传给DataFrame，pandas就会被解释为：  
        **外层字典的键作为列，内层键作为行索引**

In [48]:
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [49]:
frame3.T # 转置

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [50]:
pd.DataFrame(pop, index=[2001, 2002, 2003]) # 让行索引为固定值，即使数据值为空

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [51]:
pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada': frame3['Nevada'][:2]}

In [52]:
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [53]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [54]:
frame3.values # 返回values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [55]:
frame2.values # 可以兼容所有列的数据类型

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

## 索引对象

pandas的索引对象负责管理轴标签和其他元数据（e.g.:轴名称）。  
构建Series或DataFrame时，所用到的任何数组或其他序列的标签都会被转换成一个Index：

In [56]:
obj = pd.Series(range(3),index=['a','b','c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [57]:
index[1:]

Index(['b', 'c'], dtype='object')

Index对象是不可变的，因此用户不能对其进行修改：

In [58]:
"""
index[1] = 'd' #TypeError
"""

"\nindex[1] = 'd' #TypeError\n"

不可变可以使index对象在多个数据结构之间安全共享：

In [59]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [60]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [61]:
pd.Series([1.5, -2.5, 0])

0    1.5
1   -2.5
2    0.0
dtype: float64

In [62]:
obj2.index is labels

True

In [63]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [64]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [65]:
'Ohio' in frame3.columns

True

In [66]:
2003 in frame3.index

False

In [67]:
dup_labels = pd.Index(['foo','foo','bar','bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')