# 数组方法

In [1]:
import numpy as np
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


## 求和

In [2]:
a = array([[1,2,3],
           [4,5,6]])

In [3]:
sum(a)

21

In [4]:
sum(a,axis=0)

array([5, 7, 9])

沿着第一维度求和：

In [5]:
sum(a,axis=1)

array([ 6, 15])

沿着倒数第一维度求和：

In [6]:
sum(a,axis=-1)

array([ 6, 15])

Or

In [7]:
a.sum()

21

In [8]:
a.sum(axis=0)

array([5, 7, 9])

In [9]:
a.sum(axis=-1)

array([ 6, 15])

## 求积

In [10]:
a.prod()

720

In [11]:
prod(a,axis=0)

array([ 4, 10, 18])

## 求最大最小值

In [12]:
from numpy.random import rand

In [13]:

a = rand(3,4)
%precision 3
a

array([[0.033, 0.566, 0.628, 0.117],
       [0.884, 0.318, 0.695, 0.763],
       [0.158, 0.729, 0.67 , 0.272]])

In [14]:
a.min()

0.032682563756380345

In [15]:
a.min(axis=0)

array([0.033, 0.318, 0.628, 0.117])

In [16]:
a.max()

0.8843369780103401

In [17]:
a.max(axis=-1)

array([0.628, 0.884, 0.729])

## 寻找最大最小值的位置

`argmin`,`argmax`方法：

In [18]:
a.argmin()

0

In [19]:
a.argmin(axis=0)

array([0, 1, 0, 0], dtype=int64)

## 均值

`mean` method:

In [20]:
a = np.array([[1,2,3],[4,5,6]])

In [21]:
a.mean()

3.5

In [22]:
a.mean(axis=-1)

array([2., 5.])

或者使用 `mean` function:

In [23]:
mean(a)

3.5

In [24]:
mean(a,axis=0)

array([2.5, 3.5, 4.5])

Or use `average` function:

In [25]:
average(a)

3.5

In [26]:
average(a,axis=0)

array([2.5, 3.5, 4.5])

还支持加权平均：

In [27]:
average(a,axis=0,weights=[1,2])

array([3., 4., 5.])

## 标准差和方差

In [28]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
a.std()

1.707825127659933

In [30]:
a.std(axis=1)

array([0.816, 0.816])

In [31]:
a.var(axis=1)

array([0.667, 0.667])

In [32]:
var(a,axis=1)

array([0.667, 0.667])

## Clip Method

In [33]:
a

array([[1, 2, 3],
       [4, 5, 6]])

将数限制在某个范围：

In [34]:
a.clip(3,5) # 小于3的变为3，大于5的变为5 

array([[3, 3, 3],
       [4, 5, 5]])

## ptp Method

In [35]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
a.ptp()

5

In [37]:
a.ptp(axis=1)

array([2, 2])

## round Method

In [38]:
a = array([1.35,2.5,1.5])

In [39]:
a.round()

array([1., 2., 2.])

近似到一位小数：

In [40]:
a.round(decimals=1)

array([1.4, 2.5, 1.5])

# 总结

掌握 sum(), prod(),min(),max(), argmin(),argmax(),mean(),average(), std(), var(), clip(), ptp(), round()