# 数组类型

In [1]:
import numpy as np

## 复数数组

In [4]:
a = np.array([1+1j,2,3,4])
a

array([1.+1.j, 2.+0.j, 3.+0.j, 4.+0.j])

Python会自动判断数组类型：

In [5]:
a.dtype

dtype('complex128')

In [6]:
a.real

array([1., 2., 3., 4.])

In [7]:
a.imag

array([1., 0., 0., 0.])

In [10]:
a.imag = [1,2,3,4]

In [11]:
a

array([1.+1.j, 2.+2.j, 3.+3.j, 4.+4.j])

In [12]:
a.conj()

array([1.-1.j, 2.-2.j, 3.-3.j, 4.-4.j])

In [13]:
a = np.array([0.,1,2,3])
a.dtype

dtype('float64')

In [15]:
a.real

array([0., 1., 2., 3.])

In [17]:
a.imag

array([0., 0., 0., 0.])

In [18]:
a.conj()

array([0., 1., 2., 3.])

In [19]:
# 会报错
a.ima = [1,2,3,4]

AttributeError: 'numpy.ndarray' object has no attribute 'ima'

## 指定数组类型

In [21]:
a = np.array([0,1.0,2,3])

In [22]:
a.dtype

dtype('float64')

查看所用字节(`8 bytes * 4`):

In [23]:
a.nbytes

32

In [34]:
a = np.array([0,1,2,3])

In [32]:
a = np.array([102,111,212],dtype=uint8)
a.tofile('foo.dat')

NameError: name 'uint8' is not defined