# 数组形状

In [1]:
import numpy as np
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


## 修改数组形状

In [2]:
a = arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [3]:
a.shape = 2,3
a

array([[0, 1, 2],
       [3, 4, 5]])

`reshape`不会修改原来数组的值，只会返回一个新的数组：

In [4]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [5]:
a

array([[0, 1, 2],
       [3, 4, 5]])

`shape`和`reshape`都不能修改数组中元素的总数：

In [6]:
a.reshape(4,2)

ValueError: cannot reshape array of size 6 into shape (4,2)

## 使用newaxis增加数组维度

In [7]:
a = arange(3)
shape(a)

(3,)

In [8]:
a

array([0, 1, 2])

插入的位置不同有不同效果：

In [9]:
y = a[newaxis, :]
shape(y)

(1, 3)

In [10]:
y = a[: ,newaxis]
shape(y)

(3, 1)

In [11]:
y = a[newaxis,newaxis, : ]
shape(y)

(1, 1, 3)

## squeeze 方法去除多余的轴

In [15]:
a = arange(6)
a.shape = (2,1,3)

In [16]:
b = a.squeeze()
b.shape

(2, 3)

会返回一个将所有长度为1的维度去除的新数组。  

## 数组转置  

`transpose`返回数组的转置：

In [17]:
a

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [18]:
a.transpose()

array([[[0, 3]],

       [[1, 4]],

       [[2, 5]]])

Or

In [19]:
a.T

array([[[0, 3]],

       [[1, 4]],

       [[2, 5]]])

Note：  
   * 对于复数数组，转置并不会返回共轭，只是单纯的交换轴的位置  
   * 转置可以作用于多维数组  

In [20]:
a = arange(60)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [21]:
a.shape = 3,4,5
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [22]:
b = a.T
b.shape

(5, 4, 3)

另一方面，转置返回的是原数组的另一种view（not copy），所以会改变原来数组的值：

In [23]:
a = arange(6)
a.shape = (2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [24]:
b = a.T
b[0,1] = 30
b

array([[ 0, 30],
       [ 1,  4],
       [ 2,  5]])

In [25]:
a

array([[ 0,  1,  2],
       [30,  4,  5]])

## 数组连接

有事我们需要将不同的数组连接起来：  
    concatenate((a0,a1,...,aN), axis=0)

Note：这些数组必须要用`()`包括到一个元组中去。  



除了给定的轴外，这些数组其他轴的长度必须相等。

In [26]:
x = np.array([
              [0,1,2],
              [10,11,12]])
y = np.array([[50,51,52],
              [60,61,62]])

print(x.shape)
print(y.shape)

(2, 3)
(2, 3)


默认是沿着第一维进行连接：

In [29]:
z = concatenate((x,y))
z

array([[ 0,  1,  2],
       [10, 11, 12],
       [50, 51, 52],
       [60, 61, 62]])

In [30]:
z.shape

(4, 3)

沿着第二维进行连接:

In [31]:
z = concatenate((x,y),axis=1)
z

array([[ 0,  1,  2, 50, 51, 52],
       [10, 11, 12, 60, 61, 62]])

In [32]:
z.shape

(2, 6)

注意到`x`和`y`的形状相同，还可以将他们连接成三维的数组，但`concatenate`不能提供这个功能。  
   
   
 我们可以考虑这样：

In [33]:
z = array((x,y))
print(z)
z.shape

[[[ 0  1  2]
  [10 11 12]]

 [[50 51 52]
  [60 61 62]]]


(2, 2, 3)

事实上，**Numpy**提供了分别对应着三种情况的函数：
 * vstack
 * hstack
 * dstack

In [34]:
vstack((x,y)).shape

(4, 3)

In [35]:
hstack((x,y)).shape

(2, 6)

In [36]:
dstack((x,y)).shape

(2, 3, 2)

## Flatten 数组      

`flatten`可以将多维数组转化为1维数组：

In [37]:
a = array([[0,1],
          [2,3]])
b = a.flatten()
b

array([0, 1, 2, 3])

返回的是数组的复制，即改变`b`并不会影响`a`的值：

In [38]:
print(b)
b[0]=10
print(b)
print(a)

[0 1 2 3]
[10  1  2  3]
[[0 1]
 [2 3]]


## flat 属性  



In [39]:
a.flat

`a.flat`相当于反悔了所有元组组成的一个迭代器：

In [57]:
b = a.flat

In [41]:
b[0]

0

但此时修改`b`会改变`a`：

In [42]:
b[0]=10
print(a)

[[10  1]
 [ 2  3]]


In [43]:
a.flat[ : ]

array([10,  1,  2,  3])

## ravel 方法  

此外，还可以使用`ravel`方法，`ravel`使用高效的表示方式：

In [44]:
a = array([[0,1],
          [2,3]])
b = a.ravel()
b

array([0, 1, 2, 3])

修改`b`会改变`a`：

In [45]:
b[0]=10
a


array([[10,  1],
       [ 2,  3]])

但另一种情况：

In [46]:
a = array([[0,1],
          [2,3]])
aa = a.transpose()
print(aa)
b = aa.ravel()
b

[[0 2]
 [1 3]]


array([0, 2, 1, 3])

In [47]:
b[0]=10

In [48]:
aa

array([[0, 2],
       [1, 3]])

In [49]:
a

array([[0, 1],
       [2, 3]])

可以看出，在这种情况下，修改`b`并不会改变`aa`的值。  
这是因为我们用来`ravel`的对象`aa`本身是`a`的一个view。

## atleast_xd 函数  

保证数组至少有`x`维：

In [50]:
x = 1
atleast_1d(x)

array([1])

In [51]:
a = array([1,2,3])
b = atleast_2d(a)
b.shape

(1, 3)

In [52]:
b

array([[1, 2, 3]])

In [53]:
c = atleast_3d(b)

In [54]:
c.shape

(1, 3, 1)

In [55]:
c

array([[[1],
        [2],
        [3]]])

Note：`x`可以取值1,2,3