# 数组排列

In [1]:
import numpy as np
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


## sort函数

In [2]:
names = np.array(['bob','sue','jane','ad'])
weights = array([20.8,93.2,53.4,61.8])
sort(weights)

array([20.8, 53.4, 61.8, 93.2])

In [3]:
ordered_indices = argsort(weights)
ordered_indices

array([0, 2, 3, 1], dtype=int64)

Note：`sort`返回的值是从小到大的

## argsort函数

`argsort`返回从小到大排列后的位置

In [4]:
weights[ordered_indices]

array([20.8, 53.4, 61.8, 93.2])

In [5]:
names[ordered_indices]

array(['bob', 'jane', 'ad', 'sue'], dtype='<U4')

并不会改变原来数组的值：

In [6]:
weights

array([20.8, 93.2, 53.4, 61.8])

In [7]:
data = array([20.8,93.2,53.4,61.8])
data.argsort()

array([0, 2, 3, 1], dtype=int64)

In [8]:
data

array([20.8, 93.2, 53.4, 61.8])

In [9]:
data.sort()

In [10]:
data

array([20.8, 53.4, 61.8, 93.2])

## 二维数组排序

默认为从最后一维开始排序：  
（二维数组默认行排序）

In [11]:
a = array([[.2,.1,.5],
           [.4,.8,.3],
           [.9,.6,.7]])
a

array([[0.2, 0.1, 0.5],
       [0.4, 0.8, 0.3],
       [0.9, 0.6, 0.7]])

In [12]:
sort(a)

array([[0.1, 0.2, 0.5],
       [0.3, 0.4, 0.8],
       [0.6, 0.7, 0.9]])

改变为列排序：

In [13]:
sort(a,axis=0)

array([[0.2, 0.1, 0.3],
       [0.4, 0.6, 0.5],
       [0.9, 0.8, 0.7]])

## searchsorted 函数

    searchsorted(sorted_array,values)  

`searchsorted`接受两个参数，其中第一个必须是已排序的数组

In [14]:
sorted_array = linspace(0,1,5)
values = array([.1,.8,.3,.12,.5,.25])

In [15]:
searchsorted(sorted_array,values)

array([1, 4, 2, 1, 2, 1], dtype=int64)

In [16]:
from numpy.random import rand
data = rand(100)
print(data)
data.sort()

[0.16953578 0.42300798 0.52495012 0.08717709 0.61415543 0.41359066
 0.00687581 0.37421075 0.59397351 0.99827045 0.38452979 0.72187633
 0.89025157 0.12138489 0.84220994 0.27175908 0.36764502 0.07402132
 0.75908479 0.56504187 0.17694793 0.2360966  0.99533246 0.31024052
 0.35202153 0.30536948 0.39330778 0.34910222 0.982855   0.7971663
 0.6603681  0.70077489 0.67674709 0.8064527  0.15451268 0.37214817
 0.52501135 0.99028859 0.15751192 0.15734954 0.26458714 0.49390565
 0.91439744 0.2400222  0.48949204 0.82224901 0.89020387 0.5736976
 0.31951686 0.73192954 0.69243893 0.42426168 0.62090339 0.26621462
 0.63267252 0.88707894 0.2057533  0.96435962 0.81938866 0.26617493
 0.63522777 0.33274672 0.7125588  0.58760713 0.18108928 0.3986874
 0.89049911 0.05591754 0.04131131 0.66613999 0.27289077 0.35654662
 0.80084014 0.00660367 0.39892008 0.0410136  0.37941721 0.66036835
 0.39612515 0.56776432 0.37355158 0.40574878 0.88517316 0.39041966
 0.76278708 0.68408973 0.82741829 0.65738061 0.28169029 0.2784668

不加括号默认为元组：

In [17]:
bounds = .4, .6
bounds

(0.4, 0.6)

In [18]:
b = [.4,.6]
b

[0.4, 0.6]

In [19]:
low_idx, high_idx = searchsorted(data,bounds)

利用`low_idx`和`high_idx`插入的位置将所有在区间内的值按从小到大排序：

In [20]:
data[low_idx:high_idx]

array([0.40056068, 0.40574878, 0.41359066, 0.42300798, 0.42426168,
       0.42672714, 0.48949204, 0.49390565, 0.50428424, 0.52495012,
       0.52501135, 0.53725909, 0.56504187, 0.56776432, 0.5736976 ,
       0.58760713, 0.59397351])